# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [2]:
import torch

Construct a 5x3 matrix, uninitialized

In [3]:
x = torch.Tensor(5, 3)
print(x)

tensor([[7.8868e-37, 3.1028e-41, 1.4013e-45],
        [0.0000e+00, 7.8865e-37, 3.1028e-41],
        [7.8865e-37, 3.1028e-41, 3.3631e-44],
        [1.0653e-38, 6.1616e-36, 4.3439e-41],
        [2.8026e-45, 4.1877e-38, 0.0000e+00]])


Construct a randomly initialized matrix

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4193, 0.6919, 0.2049],
        [0.1541, 0.6849, 0.1672],
        [0.2279, 0.9655, 0.1359],
        [0.1461, 0.4890, 0.6315],
        [0.2238, 0.6095, 0.8083]])


Get its size

In [5]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [6]:
x[1:3] = 2
print(x)

tensor([[0.4193, 0.6919, 0.2049],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.1461, 0.4890, 0.6315],
        [0.2238, 0.6095, 0.8083]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [7]:
print(torch.Tensor(2, 17).size())
print(torch.FloatTensor(3, 1).size())
float_tensor = torch.LongTensor(5, 2, 1)
print(float_tensor.size())
#float_tensor.fill_(7)
float_tensor[::] = 7
print(float_tensor)
byte_tensor = torch.ByteTensor(5,)
byte_tensor[1:4] = 3
print(byte_tensor)

torch.Size([2, 17])
torch.Size([3, 1])
torch.Size([5, 2, 1])
tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])
tensor([96,  3,  3,  3, 23], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.4561, 0.9270, 0.7070],
        [2.1613, 2.3072, 2.9042],
        [2.7646, 2.1279, 2.9896],
        [0.2061, 1.0954, 1.1738],
        [0.3730, 0.7660, 1.5888]])


### 2.2 Addition: syntax 2

In [9]:
print(torch.add(x, y))

tensor([[0.4561, 0.9270, 0.7070],
        [2.1613, 2.3072, 2.9042],
        [2.7646, 2.1279, 2.9896],
        [0.2061, 1.0954, 1.1738],
        [0.3730, 0.7660, 1.5888]])


### 2.3 Addition: giving an output tensor

In [10]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.4561, 0.9270, 0.7070],
        [2.1613, 2.3072, 2.9042],
        [2.7646, 2.1279, 2.9896],
        [0.2061, 1.0954, 1.1738],
        [0.3730, 0.7660, 1.5888]])


### 2.4 Addition: in-place

adds `x`to `y`

In [11]:
y.add_(x)
print(y)

tensor([[0.4561, 0.9270, 0.7070],
        [2.1613, 2.3072, 2.9042],
        [2.7646, 2.1279, 2.9896],
        [0.2061, 1.0954, 1.1738],
        [0.3730, 0.7660, 1.5888]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [12]:
print(x[:, 1])

tensor([0.6919, 2.0000, 2.0000, 0.4890, 0.6095])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [13]:
print(torch.mul(x, y))
print(y.mul_(x))
print(torch.div(x, y))
print(torch.matmul(torch.Tensor(2,4), torch.Tensor(4,2)))

tensor([[0.1912, 0.6414, 0.1448],
        [4.3226, 4.6144, 5.8084],
        [5.5292, 4.2559, 5.9791],
        [0.0301, 0.5357, 0.7413],
        [0.0835, 0.4669, 1.2843]])
tensor([[0.1912, 0.6414, 0.1448],
        [4.3226, 4.6144, 5.8084],
        [5.5292, 4.2559, 5.9791],
        [0.0301, 0.5357, 0.7413],
        [0.0835, 0.4669, 1.2843]])
tensor([[2.1927, 1.0787, 1.4143],
        [0.4627, 0.4334, 0.3443],
        [0.3617, 0.4699, 0.3345],
        [4.8511, 0.9129, 0.8519],
        [2.6813, 1.3054, 0.6294]])
tensor([[0., 0.],
        [0., 0.]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [14]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [15]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [16]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [18]:
a = torch.ones(5,2)
b = a.numpy()
c = torch.from_numpy(b)
print(c)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [19]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

tensor([[0.4193, 0.6919, 0.2049],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.1461, 0.4890, 0.6315],
        [0.2238, 0.6095, 0.8083]], device='cuda:0')
tensor([[0.1912, 0.6414, 0.1448],
        [4.3226, 4.6144, 5.8084],
        [5.5292, 4.2559, 5.9791],
        [0.0301, 0.5357, 0.7413],
        [0.0835, 0.4669, 1.2843]], device='cuda:0')
tensor([[0.6106, 1.3332, 0.3497],
        [6.3226, 6.6144, 7.8084],
        [7.5292, 6.2559, 7.9791],
        [0.1762, 1.0247, 1.3728],
        [0.3073, 1.0764, 2.0926]], device='cuda:0')
